Failure # 1 (occurred at 2022-02-03_19-23-08)
Traceback (most recent call last):
  File "/home/huanting/SuperSonic/third_party/ray/tune/trial_runner.py", line 468, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/huanting/SuperSonic/third_party/ray/tune/ray_trial_executor.py", line 430, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/huanting/SuperSonic/third_party/ray/worker.py", line 1474, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::A3C.train()[39m (pid=79799, ip=192.168.188.130)
StopIteration

The above exception was the direct cause of the following exception:

[36mray::A3C.train()[39m (pid=79799, ip=192.168.188.130)
  File "python/ray/_raylet.pyx", line 442, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 445, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 400, in ray._raylet.execute_task.function_executor
  File "/home/huanting/SuperSonic/third_party/ray/rllib/agents/trainer.py", line 500, in train
    raise e
  File "/home/huanting/SuperSonic/third_party/ray/rllib/agents/trainer.py", line 486, in train
    result = Trainable.train(self)
  File "/home/huanting/SuperSonic/third_party/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "/home/huanting/SuperSonic/third_party/ray/rllib/agents/trainer_template.py", line 132, in _train
    return self._train_exec_impl()
  File "/home/huanting/SuperSonic/third_party/ray/rllib/agents/trainer_template.py", line 170, in _train_exec_impl
    res = next(self.train_exec_impl)
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 731, in __next__
    return next(self.built_iterator)
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 814, in apply_filter
    for item in it:
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 814, in apply_filter
    for item in it:
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
RuntimeError: generator raised StopIteration

